language: erlang
otp_release:
    - R16B
before_install:
    - git clone http://github.com/elixir-lang/elixir
    - cd elixir
    - make
    - cd ..
    - git submodule update --init --recursive
before_script:
    - export PATH=`pwd`/elixir/bin:$PATH
script:
    - mix compile
    - mix test
